set(_CATKIN_CURRENT_PACKAGE "tests")
set(tests_VERSION "0.0.0")
set(tests_MAINTAINER "root <root@todo.todo>")
set(tests_PACKAGE_FORMAT "2")
set(tests_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all-dev")
set(tests_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs")
set(tests_BUILDTOOL_DEPENDS "catkin")
set(tests_BUILDTOOL_EXPORT_DEPENDS )
set(tests_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "cv_bridge" "roscpp" "sensor_msgs" "libpcl-all")
set(tests_RUN_DEPENDS "pcl_conversions" "pcl_ros" "cv_bridge" "roscpp" "sensor_msgs" "libpcl-all")
set(tests_TEST_DEPENDS )
set(tests_DOC_DEPENDS )
set(tests_URL_WEBSITE "")
set(tests_URL_BUGTRACKER "")
set(tests_URL_REPOSITORY "")
set(tests_DEPRECATED "")